"""
peakrdl-python is a tool to generate Python Register Access Layer (RAL) from SystemRDL
Copyright (C) 2021 - 2025

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as 
published by the Free Software Foundation, either version 3 of 
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

This module is intended to distributed as part of automatically generated code by the
peakrdl-python tool. It provides a set of classes used by the autogenerated code to represent
asynchronous registers and fields
"""
from enum import Enum
from typing import Union, Optional, TypeVar, cast
from collections.abc import AsyncGenerator, Iterator, Iterable
from abc import ABC
from contextlib import asynccontextmanager
import sys
from warnings import warn

from .sections import AsyncAddressMap, AsyncRegFile
from .async_memory import  MemoryAsyncReadOnly, MemoryAsyncWriteOnly, MemoryAsyncReadWrite, \
    AsyncMemory, ReadableAsyncMemory, WritableAsyncMemory
from .callbacks import AsyncCallbackSet
from .base_register import BaseReg, BaseRegArray, RegisterWriteVerifyError
from .base_field import FieldEnum, FieldSizeProps, FieldMiscProps, \
    _FieldReadOnlyFramework, _FieldWriteOnlyFramework, FieldType
from .field_encoding import SystemRDLEnum

# pylint: disable=duplicate-code
if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self
# pylint: enable=duplicate-code

# pylint: disable=duplicate-code
if sys.version_info >= (3, 10):
    # type guarding was introduced in python 3.10
    from typing import TypeGuard
else:
    from typing_extensions import TypeGuard
# pylint: enable=duplicate-code

# pylint: disable=redefined-slots-in-subclass,too-many-lines


class AsyncReg(BaseReg,
               Iterable[Union['FieldAsyncReadOnly', 'FieldAsyncWriteOnly', 'FieldAsyncReadWrite']],
               ABC):
    """
        base class of async register wrappers

        Note:
            It is not expected that this class will be instantiated under normal
            circumstances however, it is useful for type checking
        """

    __slots__: list[str] = []

    # pylint: disable=too-many-arguments,duplicate-code
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AsyncAddressMap, AsyncRegFile, AsyncMemory, 'AsyncRegArray']):

        if not isinstance(parent, (AsyncAddressMap, AsyncRegFile,
                                   MemoryAsyncReadOnly, MemoryAsyncWriteOnly,
                                   MemoryAsyncReadWrite, AsyncRegArray)):
            raise TypeError(f'bad parent type got: {type(parent)}')

        if not isinstance(parent._callbacks, (AsyncCallbackSet)):
            raise TypeError(f'callback set type is wrong, got {type(parent._callbacks)}')

        super().__init__(address=address, logger_handle=logger_handle,
                         inst_name=inst_name, parent=parent)

    @property
    def _callbacks(self) -> Union[AsyncCallbackSet]:
        # pylint: disable=protected-access
        if self.parent is None:
            raise RuntimeError('Parent must be set')

        if isinstance(self.parent._callbacks, (AsyncCallbackSet)):
            return self.parent._callbacks

        raise TypeError(f'unhandled parent callback type: {type(self.parent._callbacks)}')

    @property
    def fields(self) -> \
            Iterator[Union['FieldAsyncReadOnly', 'FieldAsyncWriteOnly', 'FieldAsyncReadWrite']]:
        """
        generator that produces has all the fields within the register
        """
        yield from iter(self)

    @property
    def bitmask(self) -> int:
        bitmask = 0
        for field in iter(self):
            bitmask |= field.bitmask

        return bitmask

    def register_value(self, **kwargs: Union[int, 'SystemRDLEnum']) -> int:
        self._check_kwargs_field_names(**kwargs)
        register_value = 0
        for field_name, field_value in kwargs.items():
            field = getattr(self, field_name)
            register_value &= field.inverse_bitmask
            # pylint: disable=protected-access
            int_value = field._int_value(field_value)
            register_value |= field._register_bits(int_value)
            # pylint: enable=protected-access

        return register_value

    def inferred_default_register_value(self) -> int:

        register_value = 0
        for field in self.fields:
            default_value = field.default
            if default_value is None:
                continue
            register_value &= field.inverse_bitmask
            # pylint: disable=protected-access
            int_default_value = field._int_value(default_value)
            register_value |= field._register_bits(int_default_value)
            # pylint: enable=protected-access

        return register_value


class RegAsyncReadOnly(AsyncReg, ABC):
    """
    class for an async read only register

    Args:
        address: address of the register
        width: width of the register in bits
        accesswidth: minimum access width of the register in bits
        logger_handle: name to be used logging messages associate with this
            object

    """

    __slots__: list[str] = ['__in_context_manager', '__register_state']

    # pylint: disable=too-many-arguments, duplicate-code
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AsyncAddressMap, AsyncRegFile, ReadableAsyncMemory]):

        super().__init__(address=address,
                         logger_handle=logger_handle,
                         inst_name=inst_name,
                         parent=parent)

        self.__in_context_manager: bool = False
        self.__register_state: int = 0
    # pylint: enable=too-many-arguments, duplicate-code

    @asynccontextmanager
    async def single_read(self) -> AsyncGenerator[Self]:
        """
        Context manager to allow multiple field accesses to be performed with a single
        read of the register
        """
        self.__register_state = await self.read()
        # pylint: disable=duplicate-code
        self.__in_context_manager = True
        # this try/finally is needed to make sure that in the event of an exception
        # the state flags are not left incorrectly set
        try:
            yield self
        finally:
            self.__in_context_manager = False

    async def read(self) -> int:
        """
        Asynchronously read value from the register

        Returns:
            The value from register

        """
        # pylint: disable=duplicate-code
        if self.__in_context_manager:
            return self.__register_state

        read_block_callback = self._callbacks.read_block_callback
        read_callback = self._callbacks.read_callback
        # pylint: enable=duplicate-code

        if read_callback is not None:

            return await read_callback(addr=self.address,
                                       width=self.width,
                                       accesswidth=self.accesswidth)

        if read_block_callback is not None:
            array_read_result = \
                await read_block_callback(addr=self.address,
                                          width=self.width,
                                          accesswidth=self.accesswidth,
                                          length=1)
            return array_read_result[0]

        raise RuntimeError('This function does not have a useable callback')

    @property
    def readable_fields(self) -> Iterator[Union['FieldAsyncReadOnly', 'FieldAsyncReadWrite']]:
        """
        generator that produces has all the readable fields within the register
        """
        def is_readable(field: Union['FieldAsyncReadOnly',
                                     'FieldAsyncWriteOnly',
                                     'FieldAsyncReadWrite']) -> \
                TypeGuard[Union['FieldAsyncReadOnly', 'FieldAsyncReadWrite']]:
            return isinstance(field, (FieldAsyncReadOnly, FieldAsyncReadWrite))

        return filter(is_readable, self.fields)

    async def read_fields(self) -> dict['str', Union[bool, Enum, int]]:
        """
        asynchronously read the register and return a dictionary of the field values
        """
        return_dict: dict['str', Union[bool, Enum, int]] = {}
        async with self.single_read() as reg:
            for field in reg.readable_fields:
                return_dict[field.inst_name] = await field.read()

        return return_dict

    @property
    def _is_readable(self) -> bool:
        return True

    @property
    def _is_writeable(self) -> bool:
        return False

#pylint:disable-next=invalid-name
class __RegWritable(AsyncReg, ABC):
    """
    base class for a writable register (either RegAsyncWriteOnly or RegAsyncReadWrite)
    """

    __slots__: list[str] = []

    # pylint: disable=too-many-arguments, duplicate-code, useless-parent-delegation
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AsyncAddressMap, AsyncRegFile, WritableAsyncMemory]):

        super().__init__(address=address,
                         logger_handle=logger_handle,
                         inst_name=inst_name,
                         parent=parent)
    # pylint: enable=too-many-arguments, duplicate-code

    # pylint:disable=duplicate-code
    @property
    def writable_fields(self) -> Iterator[Union['FieldAsyncWriteOnly', 'FieldAsyncReadWrite']]:
        """
        generator that produces has all the writable fields within the register
        """

        def is_writable(field: Union['FieldAsyncReadOnly',
        'FieldAsyncWriteOnly',
        'FieldAsyncReadWrite']) -> \
                TypeGuard[Union['FieldAsyncWriteOnly', 'FieldAsyncReadWrite']]:
            return isinstance(field, (FieldAsyncWriteOnly, FieldAsyncReadWrite))

        return filter(is_writable, self.fields)
    # pylint:enable=duplicate-code

    async def write(self, data: int) -> None:
        """
        Writes a value to the register

        Args:
            data: data to be written

        Raises:
            ValueError: if the value provided is outside the range of the
                permissible values for the register
            TypeError: if the type of data is wrong
        """
        # this method check the types and range checks the data
        self._validate_data(data=data)

        self._logger.info(f'Writing data:0x{data:X} to 0x{self.address:X}')

        if self._callbacks.write_callback is not None:
            await self._callbacks.write_callback(addr=self.address,
                                                  width=self.width,
                                                  accesswidth=self.accesswidth,
                                                  data=data)

        elif self._callbacks.write_block_callback is not None:
            await self._callbacks.write_block_callback(addr=self.address,
                                                       width=self.width,
                                                       accesswidth=self.accesswidth,
                                                       data=[data])
        # pylint:disable=duplicate-code

        else:
            raise RuntimeError('This function does not have a useable callback')




class RegAsyncWriteOnly(__RegWritable, ABC):
    """
    class for an asynchronous write only register
    """

    __slots__: list[str] = ['__in_context_manager', '__register_state', '__write_initial_state']

    # pylint: disable=too-many-arguments, duplicate-code, useless-parent-delegation
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AsyncAddressMap, AsyncRegFile,
                               WritableAsyncMemory]):

        super().__init__(address=address,
                         logger_handle=logger_handle,
                         inst_name=inst_name,
                         parent=parent)

        self.__in_context_manager: bool = False
        self.__register_state: int = 0
        self.__write_initial_state: int = 0

    # pylint: enable=too-many-arguments, duplicate-code

    async def write(self, data: int) -> None:
        """
        Writes a value to the register

        Args:
            data: data to be written

        Raises:
            ValueError: if the value provided is outside the range of the
                        permissible values for the register
            TypeError: if the type of data is wrong
            RegisterWriteVerifyError: the read back data after the write does not match the
                                      expected value
            RuntimeError: if the read verify after write is set when inside a context manager
        """


        if self.__in_context_manager:
            self.__register_state = data
        else:
            await super().write(data)

    @property
    def write_initial_state(self) -> int:
        """
        This property defines the initial state of the register when using:
        - the `write_fields` method
        - the `write` method on any field in the register

        By default this is initialised to `0`, however, advanced usages may include:
        - A hidden field within the register which must not be set to `0`

        This property behaves accessed when inside the `single_write` when it returns the shadowed
        state of the register which has not yet been writen back (the initial state plus any write
        that has occurred). However, setting the property will still update the initial state not
        the shadowed state.
        """
        # This function by its nature is very similar to the non-async version
        # pylint: disable=duplicate-code

        if self.__in_context_manager:
            return self.__register_state
        return self.__write_initial_state

    @write_initial_state.setter
    def write_initial_state(self, initial_state: int) -> None:
        # This function by its nature is very similar to the non-async version
        # pylint: disable=duplicate-code

        # this method check the types and range checks the data
        self._validate_data(data=initial_state)
        self.__write_initial_state = initial_state

    async def write_fields(self, **kwargs: Union[int, SystemRDLEnum]) -> None:
        """
        Do a single write to the register based on the fields provided, all fields must be
        specified to use this method

        Any parts of the register not set with this method will be based on the
        `write_initial_state` property
        """
        self._check_kwargs_field_names(**kwargs)

        async with self.single_write(initial_state=self.write_initial_state) as reg:
            for field_name, field_value in kwargs.items():
                if field_name not in reg.systemrdl_python_child_name_map.values():
                    raise ValueError(f'{field_name} is not a member of the register')

                field = getattr(reg, field_name)
                await field.write(field_value)

    @asynccontextmanager
    async def single_write(self, initial_state: int) -> AsyncGenerator[Self]:
        """
        Context manager to allow multiple field write operations to be carried out with a
        single write at the end, based on a specified initial state of the register.
        """
        # This function by its nature is very similar to the non-async version
        # pylint: disable=duplicate-code

        # this method check the types and range checks the data
        self._validate_data(data=initial_state)

        self.__register_state = initial_state
        self.__in_context_manager = True
        # this try/finally is needed to make sure that in the event of an exception
        # the state flags are not left incorrectly set
        try:
            yield self
        finally:
            self.__in_context_manager = False
        await self.write(self.__register_state)

    @property
    def _is_readable(self) -> bool:
        return False

    @property
    def _is_writeable(self) -> bool:
        return True


class RegAsyncReadWrite(RegAsyncReadOnly, __RegWritable, ABC):
    """
    class for an async read and write only register

    """
    __slots__: list[str] = ['__in_read_context_manager',
                            '__in_write_context_manager',
                            '__register_state',
                            '__write_initial_state']

    # pylint: disable=too-many-arguments, duplicate-code
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AsyncAddressMap, AsyncRegFile, MemoryAsyncReadWrite]):

        super().__init__(address=address,
                         logger_handle=logger_handle,
                         inst_name=inst_name,
                         parent=parent)

        self.__in_read_context_manager: bool = False
        self.__in_write_context_manager: bool = False
        self.__register_state: Optional[int] = None
        self.__write_initial_state = 0

    # pylint: enable=too-many-arguments, duplicate-code

    @asynccontextmanager
    async def single_read_modify_write(self, verify: bool = False) -> AsyncGenerator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single register read
        and write

        Args:
            verify (bool): verify the write with a read afterwards
        """
        initial_state = await self.read()
        async with self.single_write(initial_state=initial_state, verify=verify) as reg:
            yield reg

    @asynccontextmanager
    async def single_read(self) -> AsyncGenerator[Self]:
        """
        Context manager to allow multiple field reads with a single register read
        """
        # This function by its nature is very similar to the non-async version
        # pylint: disable=duplicate-code
        if self.__in_read_context_manager:
            raise RuntimeError('using the `single_read` context manager double layered is '
                               'not permitted')

        if self.__in_write_context_manager:
            raise RuntimeError('using the `single_read` context manager within the '
                               'single_read_modify_write` or `single_write` is not permitted')
        self.__in_read_context_manager = True
        try:
            async with super().single_read() as reg:
                yield reg
        finally:
            self.__in_read_context_manager = False

    @asynccontextmanager
    async def single_write(self, initial_state: int, verify: bool = False) -> AsyncGenerator[Self]:
        """
        Context manager to allow multiple field updates with a single register write when the
         context manager exits
        """
        # This function is by its nature very similar to the non-async version
        # pylint: disable=duplicate-code
        if self.__in_write_context_manager or self.__in_read_context_manager:
            raise RuntimeError('using the `single_write` context manager within the '
                               'single_read_modify_write` or `single_read` is not permitted. '
                               'Similarly, using the `single_write` context manager within itself '
                               'is not permitted')
        self.__in_write_context_manager = True
        self.__register_state = initial_state
        try:
            yield self
        finally:
            self.__in_write_context_manager = False
        await self.write(self.__register_state, verify=verify)

        # clear the register states at the end of the context manager
        self.__register_state = None

    async def write(self, data: int, verify: bool = False) -> None:  # pylint: disable=arguments-differ
        """
        Writes a value to the register

        Args:
            data: data to be written
            verify: set to True to read back the register to verify the read has occurred correctly

        Raises:
            ValueError: if the value provided is outside the range of the
                        permissible values for the register
            TypeError: if the type of data is wrong
            RegisterWriteVerifyError: the read back data after the write does not match the
                                      expected value
            RuntimeError: if the read verify after write is set when inside a context manager
        """
        # This function is by its nature very similar to the non-async version
        # pylint: disable=duplicate-code
        if self.__in_read_context_manager:
            raise RuntimeError('writes within the single read context manager are not permitted')

        if self.__in_write_context_manager:
            if self.__register_state is None:
                raise RuntimeError('The internal register state should never be None in the '
                                   'context manager')
            if verify:
                raise RuntimeError('Using the verify option is not permitted inside the '
                                   '`single_write` or `single_read_modify_write` context manager')

            self.__register_state = data
        else:
            await super().write(data)
            if verify:
                read_back = await self.read()
                if read_back != data:
                    raise RegisterWriteVerifyError(f'Readback {read_back:X} '
                                                   f'after writing {data:X}')

    async def read(self) -> int:
        """
        Read value from the register

        Note:
            The `read` method behaves differently when used within the one of the context managers:
            - when used within `single_read_modify_write` or `single_read` it will return the
              register value read at the entry into the context manager
            - when used within `single_write` it will return the register value based on the
              `initial_state` argument provided with the context manager
        """
        # This function by its nature is very similar to the non-async version
        # pylint: disable=duplicate-code
        if self.__in_write_context_manager:
            if self.__register_state is None:
                raise RuntimeError('The internal register state should never be None in the '
                                   'context manager')
            return self.__register_state

        # the single read context manager is handled in the base class so does need any
        # handling here

        return await super().read()

    async def write_fields(self, **kwargs: Union[int, SystemRDLEnum]) -> None:
        """
        Do a read-modify-write to the register, updating any field included in
        the arguments
        """
        if len(kwargs) == 0:
            raise ValueError('no command args')

        async with self.single_read_modify_write() as reg:
            for field_name, field_value in kwargs.items():
                if field_name not in reg.systemrdl_python_child_name_map.values():
                    raise ValueError(f'{field_name} is not a member of the register')

                field = getattr(reg, field_name)
                await field.write(field_value)

    async def read_fields(self) -> dict['str', Union[bool, Enum, int]]:
        """
        read the register and return a dictionary of the field values
        """
        # This function by its nature is very similar to the non-async version
        # pylint: disable=duplicate-code
        return_dict: dict['str', Union[bool, Enum, int]] = {}
        async with self.single_read() as reg:
            for field in reg.readable_fields:
                return_dict[field.inst_name] = await field.read()

        return return_dict

    async def write_all_fields_without_read(self, **kwargs: int) -> None:
        """
        Do a write to all the fields in a register, updating any field included in
        the arguments based on the starting state of `write_initial_state`
        """
        # This function by its nature is very similar to the non-async version
        # pylint: disable=duplicate-code

        # This method should only be called with a complete set of fields specified
        called_keys = set(kwargs.keys())
        expected_keys = set(self.systemrdl_python_child_name_map.values())
        if called_keys != expected_keys:
            raise RuntimeError(f'{called_keys} mismatches the set of '
                               f'expected keys: {expected_keys}')
        async with self.single_write(initial_state=self.write_initial_state) as reg:
            for field_name, field_value in kwargs.items():
                if field_name not in reg.systemrdl_python_child_name_map.values():
                    raise ValueError(f'{field_name} is not a member of the register')

                field = getattr(reg, field_name)
                await field.write(field_value)

    @property
    def write_initial_state(self) -> int:
        """
        This property defines the initial state of the register when using the
        `write_all_fields_without_read` method before any updates are applied.
        """
        return self.__write_initial_state

    @write_initial_state.setter
    def write_initial_state(self, initial_state: int) -> None:
        # this method check the types and range checks the data
        self._validate_data(data=initial_state)
        self.__write_initial_state = initial_state

    @property
    def _is_readable(self) -> bool:
        return True

    @property
    def _is_writeable(self) -> bool:
        return True


ReadableAsyncRegister = Union[RegAsyncReadOnly, RegAsyncReadWrite]
WritableAsyncRegister = Union[RegAsyncWriteOnly, RegAsyncReadWrite]


# pylint: disable-next=invalid-name
AsyncRegArrayElementType= TypeVar('AsyncRegArrayElementType', bound=AsyncReg)


class AsyncRegArray(BaseRegArray[AsyncRegArrayElementType], ABC):
    """
    base class of register array wrappers

    Note:
        It is not expected that this class will be instantiated under normal
        circumstances however, it is useful for type checking
    """
    # pylint: disable=too-many-arguments,duplicate-code

    __slots__: list[str] = ['__in_context_manager', '__register_cache',
                            '__register_address_array']

    def __init__(self, *,
                 logger_handle: str, inst_name: str,
                 parent: Union[AsyncAddressMap, AsyncRegFile, AsyncMemory],
                 address: int,
                 stride: int,
                 dimensions: tuple[int, ...],
                 elements: Optional[tuple[tuple[tuple[int, ...], ...],
                                    tuple[AsyncRegArrayElementType, ...]]] = None):

        self.__in_context_manager: bool = False
        self.__register_cache: Optional[list[int]] = None
        self.__register_address_array: Optional[list[int]] = None

        if not isinstance(parent._callbacks, AsyncCallbackSet):
            raise TypeError(f'callback set type is wrong, got {type(parent._callbacks)}')

        super().__init__(logger_handle=logger_handle, inst_name=inst_name,
                         parent=parent, address=address,
                         stride=stride, dimensions=dimensions, elements=elements)

    @property
    def __empty_cache(self) -> list[int]:
        return [0 for _ in range(self.__number_cache_entries)]

    async def __block_read(self) -> list[int]:
        """
        Read all the contents of the array in the most optimal way, ideally with a block operation
        """
        read_block_callback = self._callbacks.read_block_callback
        read_callback = self._callbacks.read_callback

        if read_block_callback is not None:
            data_read = await read_block_callback(
                addr=self.address,
                width=self.width,
                accesswidth=self.accesswidth,
                length=self.__number_cache_entries)

            if not isinstance(data_read, list):
                raise TypeError('The read block callback is expected to return an array')

            return data_read

        if read_callback is not None:
            # there is not read_block_callback defined so we must used individual read
            data_list = self.__empty_cache

            if self.__register_address_array is None:
                raise RuntimeError('This address array has not be initialised')

            for entry, address in enumerate(self.__register_address_array):
                data = await read_callback(addr=address,
                                           width=self.width,
                                           accesswidth=self.accesswidth)

                data_list[entry] = data

            return data_list

        raise RuntimeError('There is no usable callback')

    async def __block_write(self, data: list[int], verify: bool) -> None:
        """
        Write all the contents of the array in the most optimal way, ideally with a block operation
        """
        write_block_callback = self._callbacks.write_block_callback
        write_callback = self._callbacks.write_callback

        if write_block_callback is not None:
            await write_block_callback(addr=self.address,
                                       width=self.width,
                                       accesswidth=self.width,
                                       data=data)
        elif write_callback is not None:
            # there is not write_block_callback defined so we must used individual write

            if self.__register_address_array is None:
                raise RuntimeError('This address array has not be initialised')

            for entry_index, entry_data in enumerate(data):
                entry_address = self.__register_address_array[entry_index]
                await write_callback(addr=entry_address,
                                     width=self.width,
                                     accesswidth=self.accesswidth,
                                     data=entry_data)

        else:
            raise RuntimeError('No suitable callback')

        if verify:
            read_back_verify_data = self.__block_read()
            if read_back_verify_data != data:
                raise RegisterWriteVerifyError('Read back block miss-match')

    def __cache_entry(self, addr: int, width: int, accesswidth: int) -> int:
        """
        Validate the data provided and determine the cache entry

        Args:
            addr: Address to write to
            width: Width of the register in bits
            accesswidth: Minimum access width of the register in bits

        Returns:
            cache entry

        """
        if not isinstance(width, int):
            raise TypeError(f'Width should be an int byt got {type(width)}')
        if width != self.width:
            raise ValueError('Requested Read width does not match the expected value')
        if not isinstance(accesswidth, int):
            raise TypeError(f'accesswidth should be an int byt got {type(accesswidth)}')
        if accesswidth != self.accesswidth:
            raise ValueError('Requested Read accesswidth does not match the expected value')
        if not isinstance(addr, int):
            raise TypeError(f'addr should be an int byt got {type(addr)}')
        if not self.address <= addr < (self.address + self.size):
            raise ValueError(f'Requested address 0x{addr:X} is out of range 0x{self.address:X} to '
                             f'0x{self.address + self.size - (self.width >> 3):X}')
        cache_entry = (addr - self.address) // (self.width >> 3)
        if self.__register_address_array is None:
            raise RuntimeError('The address table should always be populated here')
        if self.__register_address_array[cache_entry] != addr:
            raise RuntimeError(f'The calculated cache entry for address 0x{addr:X}')
        return cache_entry

    async def __cache_read(self, addr: int, width: int, accesswidth: int) -> int:
        """
        Used to replace the normal callbacks with those that access the cache

        Args:
            addr: Address to write to
            width: Width of the register in bits
            accesswidth: Minimum access width of the register in bits

        Returns:
            value inputted by the used
        """
        if self.__register_cache is None:
            raise RuntimeError('The cache array should be initialised')
        return self.__register_cache[self.__cache_entry(addr=addr,
                                                        width=width,
                                                        accesswidth=accesswidth)]

    async def __cache_write(self, addr: int, width: int, accesswidth: int, data: int) -> None:
        """
        Used to replace the normal callbacks with those that access the cache

        Args:
            addr: Address to write to
            width: Width of the register in bits
            accesswidth: Minimum access width of the register in bits
            data: value to be written to the register

        Returns:
            None
        """
        if not isinstance(data, int):
            raise TypeError(f'Data should be an int byt got {type(data)}')
        if self.__register_cache is None:
            raise RuntimeError('The cache array should be initialised')
        self.__register_cache[self.__cache_entry(addr=addr,
                                                 width=width,
                                                 accesswidth=accesswidth)] = data

    @property
    def __cache_callbacks(self) -> AsyncCallbackSet:
        return AsyncCallbackSet(read_callback=self.__cache_read,
                                write_callback=self.__cache_write)

    @property
    def __number_cache_entries(self) -> int:
        return self.size // (self.width >> 3)

    async def __initialise_cache(self, skip_initial_read: bool) -> list[int]:
        if skip_initial_read:
            return self.__empty_cache
        return await self.__block_read()


    @asynccontextmanager
    async def _cached_access(self, verify: bool = False, skip_write: bool = False,
                             skip_initial_read: bool = False) -> \
            AsyncGenerator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single set of
        field operations

        Args:
            verify (bool): very the write with a read afterwards
            skip_write (bool): skip the write back at the end

        """
        self.__register_address_array = \
            [self.address + (i * (self.width >> 3)) for i in range(self.__number_cache_entries)]
        self.__register_cache = await self.__initialise_cache(skip_initial_read=skip_initial_read)
        self.__in_context_manager = True
        # this try/finally is needed to make sure that in the event of an exception
        # the state flags are not left incorrectly set
        try:
            yield self
        finally:
            self.__in_context_manager = False
        if not skip_write:
            if not isinstance(self.__register_cache, list):
                raise TypeError('Register cache should be a list in non-legacy mode')
            await self.__block_write(self.__register_cache, verify)


        # clear the register states at the end of the context manager
        self.__register_address_array = None
        self.__register_cache = None

    @property
    def _callbacks(self) -> AsyncCallbackSet:
        # pylint: disable=protected-access
        if self.__in_context_manager:
            return self.__cache_callbacks

        if self.parent is None:
            raise RuntimeError('Parent must be set')

        if isinstance(self.parent._callbacks, AsyncCallbackSet):
            return self.parent._callbacks

        raise TypeError(f'unhandled parent callback type: {type(self.parent._callbacks)}')


class RegAsyncReadOnlyArray(AsyncRegArray[RegAsyncReadOnly], ABC):
    """
    base class for a array of async read only registers
    """
    __slots__: list[str] = []

    # pylint: disable=too-many-arguments,duplicate-code
    def __init__(self, *,
                 logger_handle: str, inst_name: str,
                 parent: Union[AsyncRegFile, AsyncAddressMap, ReadableAsyncMemory],
                 address: int,
                 stride: int,
                 dimensions: tuple[int, ...],
                 elements: Optional[tuple[tuple[tuple[int, ...], ...],
                                          tuple[RegAsyncReadOnly, ...]]] = None):

        if not isinstance(parent, (AsyncRegFile, AsyncAddressMap,
                                   MemoryAsyncReadOnly,
                                   MemoryAsyncReadWrite)):
            raise TypeError('parent should be either AsyncRegFile, AsyncAddressMap, '
                            'MemoryAsyncReadOnly, MemoryAsyncReadWrite '
                            f'got {type(parent)}')

        super().__init__(logger_handle=logger_handle, inst_name=inst_name,
                         parent=parent, address=address,
                         stride=stride, dimensions=dimensions, elements=elements)
    # pylint: enable=too-many-arguments,duplicate-code

    @asynccontextmanager
    async def single_read(self) -> AsyncGenerator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single set of
        field operations

        Args:


        Returns:

        """
        async with self._cached_access(verify=False, skip_write=True,
                                       skip_initial_read=False) as reg_array:
            yield reg_array

    # These properties are by their nature very similar to the non-async version
    # pylint: disable=duplicate-code
    @property
    def _is_readable(self) -> bool:
        return True

    @property
    def _is_writeable(self) -> bool:
        return False
    # pylint: enable=duplicate-code


class RegAsyncWriteOnlyArray(AsyncRegArray[RegAsyncWriteOnly], ABC):
    """
    base class for a array of async write only registers
    """
    __slots__: list[str] = []

    # pylint: disable=too-many-arguments,duplicate-code
    def __init__(self, *,
                 logger_handle: str, inst_name: str,
                 parent: Union[AsyncRegFile, AsyncAddressMap,
                               WritableAsyncMemory],
                 address: int,
                 stride: int,
                 dimensions: tuple[int, ...],
                 elements: Optional[tuple[tuple[tuple[int, ...], ...],
                                          tuple[RegAsyncWriteOnly, ...]]] = None):

        if not isinstance(parent, (AsyncRegFile, AsyncAddressMap,
                                   MemoryAsyncWriteOnly, MemoryAsyncReadWrite)):
            raise TypeError('parent should be either AsyncRegFile, AsyncAddressMap, '
                            'MemoryAsyncWriteOnly, MemoryAsyncReadWrite '
                            f'got {type(parent)}')

        super().__init__(logger_handle=logger_handle, inst_name=inst_name,
                         parent=parent, address=address,
                         stride=stride, dimensions=dimensions, elements=elements)
    # pylint: enable=too-many-arguments,duplicate-code

    @asynccontextmanager
    async def single_write(self) -> AsyncGenerator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single set of
        field operations

        Args:


        Returns:

        """
        async with self._cached_access(verify=False, skip_write=False,
                                       skip_initial_read=True) as reg_array:
            yield reg_array

    @property
    def _is_readable(self) -> bool:
        return False

    @property
    def _is_writeable(self) -> bool:
        return True


class RegAsyncReadWriteArray(AsyncRegArray[RegAsyncReadWrite], ABC):
    """
    base class for a array of read and write registers
    """
    __slots__: list[str] = []

    # pylint: disable=too-many-arguments,duplicate-code
    def __init__(self, *,
                 logger_handle: str, inst_name: str,
                 parent: Union[AsyncRegFile, AsyncAddressMap, MemoryAsyncReadWrite],
                 address: int,
                 stride: int,
                 dimensions: tuple[int, ...],
                 elements: Optional[tuple[tuple[tuple[int, ...]],
                                          tuple[RegAsyncReadWrite]]] = None):

        if not isinstance(parent, (AsyncRegFile, AsyncAddressMap, MemoryAsyncReadWrite)):
            raise TypeError('parent should be either AsyncRegFile, AsyncAddressMap, '
                            'MemoryAsyncReadWrite '
                            f'got {type(parent)}')

        super().__init__(logger_handle=logger_handle, inst_name=inst_name,
                         parent=parent, address=address,
                         stride=stride, dimensions=dimensions, elements=elements)
    # pylint: enable=too-many-arguments,duplicate-code

    @asynccontextmanager
    async def single_read_modify_write(self, verify: bool = False, skip_write: bool = False) -> \
            AsyncGenerator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single set of
        field operations

        Args:
            verify (bool): very the write with a read afterwards
            skip_write (bool): skip the write back at the end

        Returns:

        """
        if skip_write is True:
            warn('The `skip_write` argument will be removed in the future, use `single_read`'
                 ' instead',
                 DeprecationWarning, stacklevel=2)

        async with self._cached_access(verify=verify, skip_write=skip_write,
                                       skip_initial_read=False) as reg_array:
            yield reg_array

    @property
    def _is_readable(self) -> bool:
        return True

    @property
    def _is_writeable(self) -> bool:
        return True


ReadableAsyncRegisterArray = Union[RegAsyncReadOnlyArray, RegAsyncReadWriteArray]
WriteableAsyncRegisterArray = Union[RegAsyncWriteOnlyArray, RegAsyncReadWriteArray]


class FieldAsyncReadOnly(_FieldReadOnlyFramework[FieldType], ABC):
    """
    class for an asynchronous read only register field

    Args:
        parent_register: register within which the field resides
        size_props: object defining the msb, lsb, high bit, low bit and width
        logger_handle: name to be used logging messages associate with this
            object

    """
    __slots__: list[str] = []

    # pylint: disable-next=too-many-arguments
    def __init__(self, *,
                 parent_register: ReadableAsyncRegister,
                 size_props: FieldSizeProps,
                 misc_props: FieldMiscProps,
                 logger_handle: str,
                 inst_name: str,
                 field_type:type[FieldType]):

        if not isinstance(parent_register, (RegAsyncReadWrite, RegAsyncReadOnly)):
            raise TypeError(f'size_props must be of {type(RegAsyncReadWrite)} or '
                            f'{type(RegAsyncReadOnly)} but got {type(parent_register)}')

        # pylint: disable=duplicate-code
        super().__init__(logger_handle=logger_handle,
                         size_props=size_props,
                         misc_props=misc_props,
                         parent_register=parent_register,
                         inst_name=inst_name,
                         field_type=field_type)
        # pylint: enable=duplicate-code

    async def read(self) -> FieldType:  # pylint: disable=invalid-overridden-method
        """
        Asynchronously reads the register that this field is located in and retries the field
        value applying the required masking and shifting

        Returns:
            field value

        """
        return self._decode_read_value(await self.parent_register.read())

    @property
    def parent_register(self) -> ReadableAsyncRegister:
        """
        parent register the field is placed in
        """

        # this cast is OK because an explict typing check was done in the __init__
        return cast(ReadableAsyncRegister, self.parent)


class FieldAsyncWriteOnly(_FieldWriteOnlyFramework[FieldType], ABC):
    """
    class for an asynchronous write only register field

    Args:
        parent_register: register within which the field resides
        size_props: object defining the msb, lsb, high bit, low bit and width
        logger_handle: name to be used logging messages associate with this
            object

    """
    __slots__: list[str] = []

    # pylint: disable-next=too-many-arguments
    def __init__(self, *,
                 parent_register: WritableAsyncRegister,
                 size_props: FieldSizeProps,
                 misc_props: FieldMiscProps,
                 logger_handle: str,
                 inst_name: str,
                 field_type:type[FieldType]):

        if not isinstance(parent_register, (RegAsyncReadWrite, RegAsyncWriteOnly)):
            raise TypeError(f'size_props must be of {type(RegAsyncReadWrite)} or '
                            f'{type(RegAsyncWriteOnly)} but got {type(parent_register)}')

        # pylint: disable=duplicate-code
        super().__init__(logger_handle=logger_handle,
                         size_props=size_props,
                         misc_props=misc_props,
                         parent_register=parent_register,
                         inst_name=inst_name,
                         field_type=field_type)
        # pylint: enable=duplicate-code

    async def write(self, value: FieldType, verify: bool = False,
                    force_no_read: bool = False) -> None:
        """
        The behaviour of this method depends on whether the field is located in
        a readable register or not:

        If the register is readable, the method will perform a read-modify-write
        on the register updating the field with the value provided, unless force_no_read` is set
        to `True` in which case the register `write_initial_state` is used

        If the register is not writable, all other field values will be written
        with based on the register `write_initial_state`.

        Args:
            value: field value to update to
            verify: Read back the register value to confirm the write was successful
            force_no_read: prevents a pre-write read in the case of a Read/Write Register

        Raises:
            ValueError: if verify is turned on for a Write Only register

        """
        # This function by its nature is very similar to the non-async version
        # pylint: disable=duplicate-code
        encoded_value = self._encode_write_value(value)

        if (self.high == (self.register_data_width - 1)) and (self.low == 0):
            # special case where the field occupies the whole register,
            # there a straight write can be performed
            new_reg_value = encoded_value
        else:
            # do a read, modify write
            if isinstance(self.parent_register, RegAsyncReadWrite) and not force_no_read:
                reg_value = await self.parent_register.read()
                masked_reg_value = reg_value & self.inverse_bitmask
                new_reg_value = masked_reg_value | encoded_value
            elif (isinstance(self.parent_register, RegAsyncWriteOnly) or
                  (isinstance(self.parent_register, RegAsyncReadWrite) and force_no_read)):
                reg_value = self.parent_register.write_initial_state
                masked_reg_value = reg_value & self.inverse_bitmask
                new_reg_value = masked_reg_value | encoded_value
            else:
                raise TypeError('Unhandled parent type')

        if isinstance(self.parent_register, RegAsyncReadWrite):
            await self.parent_register.write(new_reg_value, verify=verify)
        elif isinstance(self.parent_register, RegAsyncWriteOnly):
            if verify:
                raise ValueError('A post-write verify (read) can not be performed on a write-only '
                                 'register')
            await self.parent_register.write(new_reg_value)

    @property
    def parent_register(self) -> WritableAsyncRegister:
        """
        parent register the field is placed in
        """

        # this cast is OK because an explict typing check was done in the __init__
        return cast(WritableAsyncRegister, self.parent)


class FieldAsyncReadWrite(FieldAsyncReadOnly[FieldType], FieldAsyncWriteOnly[FieldType], ABC):
    """
    class for an asynchronous read/write register field

    Args:
        parent_register: register within which the field resides
        size_props: object defining the msb, lsb, high bit, low bit and width
        logger_handle: name to be used logging messages associate with this
            object

    """
    __slots__: list[str] = []

    # pylint: disable-next=too-many-arguments
    def __init__(self, *,
                 parent_register: RegAsyncReadWrite,
                 size_props: FieldSizeProps,
                 misc_props: FieldMiscProps,
                 logger_handle: str,
                 inst_name: str,
                 field_type:type[FieldType]):

        if not isinstance(parent_register, RegAsyncReadWrite):
            raise TypeError(f'size_props must be of {type(RegAsyncReadWrite)} '
                            f'but got {type(parent_register)}')

        # pylint: disable=duplicate-code
        super().__init__(logger_handle=logger_handle,
                         size_props=size_props,
                         misc_props=misc_props,
                         parent_register=parent_register,
                         inst_name=inst_name,
                         field_type=field_type)
        # pylint: enable=duplicate-code

    @property
    def parent_register(self) -> RegAsyncReadWrite:
        """
        parent register the field is placed in
        """

        # this cast is OK because an explict typing check was done in the __init__
        return cast(RegAsyncReadWrite, self.parent)


class FieldEnumAsyncReadWrite(FieldAsyncReadWrite[FieldType], FieldEnum[FieldType], ABC):
    """
    class for an async read/write register field with an enumerated value
    """
    __slots__: list[str] = []

    @property
    def parent_register(self) -> RegAsyncReadWrite:
        """
        parent register the field is placed in
        """

        # this cast is OK because an explict typing check was done in the __init__
        return cast(RegAsyncReadWrite, self.parent)


class FieldEnumAsyncReadOnly(FieldAsyncReadOnly[FieldType], FieldEnum[FieldType], ABC):
    """
    class for an async read only register field with an enumerated value
    """
    __slots__: list[str] = []


class FieldEnumAsyncWriteOnly(FieldAsyncWriteOnly[FieldType], FieldEnum[FieldType], ABC):
    """
    class for an async write only register field with an enumerated value
    """
    __slots__: list[str] = []
