"""
peakrdl-python is a tool to generate Python Register Access Layer (RAL) from SystemRDL
Copyright (C) 2021 - 2025

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as 
published by the Free Software Foundation, either version 3 of 
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

This module is intended to distributed as part of automatically generated code by the
peakrdl-python tool. It provides a set of classes used by the autogenerated code to represent
registers and fields
"""
from enum import Enum
from typing import Union, cast, Optional, TypeVar
from collections.abc import Generator, Iterator, Iterable
from abc import ABC
from contextlib import contextmanager
import sys

from .sections import AddressMap, RegFile
from .memory import  MemoryReadOnly, MemoryWriteOnly, MemoryReadWrite, Memory, \
    ReadableMemory, WritableMemory
from .callbacks import NormalCallbackSet
from .base_register import BaseReg, BaseRegArray, RegisterWriteVerifyError
from .base_field import FieldEnum, FieldSizeProps, FieldMiscProps, \
    _FieldReadOnlyFramework, _FieldWriteOnlyFramework, FieldType
from .field_encoding import SystemRDLEnum

# pylint: disable=duplicate-code
if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self
# pylint: enable=duplicate-code

# pylint: disable=duplicate-code
if sys.version_info >= (3, 10):
    # type guarding was introduced in python 3.10
    from typing import TypeGuard
else:
    from typing_extensions import TypeGuard
# pylint: enable=duplicate-code

# pylint: disable=redefined-slots-in-subclass,too-many-lines


class Reg(BaseReg, Iterable[Union['FieldReadOnly', 'FieldWriteOnly', 'FieldReadWrite']], ABC):
    """
        base class of non-async register wrappers
        """

    __slots__: list[str] = []

    # pylint: disable=too-many-arguments,duplicate-code
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AddressMap, RegFile, Memory, 'RegArray']):

        if not isinstance(parent, (AddressMap, RegFile, RegArray,
                                   MemoryReadOnly, MemoryWriteOnly, MemoryReadWrite, )):
            raise TypeError(f'bad parent type got: {type(parent)}')

        if not isinstance(parent._callbacks, NormalCallbackSet):
            raise TypeError(f'callback set type is wrong, got {type(parent._callbacks)}')

        super().__init__(address=address, logger_handle=logger_handle,
                         inst_name=inst_name, parent=parent)

    @property
    def _callbacks(self) -> NormalCallbackSet:
        # pylint: disable=protected-access
        if self.parent is None:
            raise RuntimeError('Parent must be set')

        if isinstance(self.parent._callbacks, NormalCallbackSet):
            return self.parent._callbacks

        raise TypeError(f'unhandled parent callback type: {type(self.parent._callbacks)}')

    @property
    def fields(self) -> Iterator[Union['FieldReadOnly', 'FieldWriteOnly', 'FieldReadWrite']]:
        """
        generator that produces has all the fields within the register
        """
        yield from iter(self)

    @property
    def bitmask(self) -> int:
        bitmask = 0
        for field in iter(self):
            bitmask |= field.bitmask

        return bitmask

    def register_value(self, **kwargs: Union[int, SystemRDLEnum]) -> int:
        self._check_kwargs_field_names(**kwargs)
        register_value = 0
        for field_name, field_value in kwargs.items():
            field = getattr(self, field_name)
            register_value &= field.inverse_bitmask
            # pylint: disable=protected-access
            int_value = field._int_value(field_value)
            register_value |= field._register_bits(int_value)
            # pylint: enable=protected-access

        return register_value

    def inferred_default_register_value(self) -> int:

        register_value = 0
        for field in self.fields:
            default_value = field.default
            if default_value is None:
                continue
            register_value &= field.inverse_bitmask
            # pylint: disable=protected-access
            int_default_value = field._int_value(default_value)
            register_value |= field._register_bits(int_default_value)
            # pylint: enable=protected-access

        return register_value

# pylint: disable-next=invalid-name
RegArrayElementType= TypeVar('RegArrayElementType', bound=BaseReg)


class RegArray(BaseRegArray[RegArrayElementType], ABC):
    """
    base class of register array wrappers
    """
    # pylint: disable=too-many-arguments,duplicate-code

    __slots__: list[str] = ['__in_context_manager', '__register_cache',
                            '__register_address_array']

    def __init__(self, *,
                 logger_handle: str, inst_name: str,
                 parent: Union[AddressMap, RegFile, Memory],
                 address: int,
                 stride: int,
                 dimensions: tuple[int, ...],
                 elements: Optional[tuple[tuple[tuple[int, ...], ...],
                                          tuple[RegArrayElementType, ...]]] = None):

        self.__in_context_manager: bool = False
        self.__register_cache: Optional[list[int]] = None
        self.__register_address_array: Optional[list[int]] = None

        if not isinstance(parent._callbacks, NormalCallbackSet):
            raise TypeError(f'callback set type is wrong, got {type(parent._callbacks)}')

        super().__init__(logger_handle=logger_handle, inst_name=inst_name,
                         parent=parent, address=address,
                         stride=stride, dimensions=dimensions, elements=elements)

    @property
    def __empty_cache(self) -> list[int]:
        return [0 for _ in range(self.__number_cache_entries)]

    def __block_read(self) -> list[int]:
        """
        Read all the contents of the array in the most optimal way, ideally with a block operation
        """
        read_block_callback = self._callbacks.read_block_callback
        read_callback = self._callbacks.read_callback

        if read_block_callback is not None:
            data_read = \
                read_block_callback(addr=self.address,
                                    width=self.width,
                                    accesswidth=self.accesswidth,
                                    length=self.__number_cache_entries)

            if not isinstance(data_read, list):
                raise TypeError('The read block callback is expected to return an list')
            return data_read

        if read_callback is not None:
            # there is not read_block_callback defined so we must used individual read
            data_list = self.__empty_cache

            if self.__register_address_array is None:
                raise RuntimeError('This address array has not be initialised')

            for entry, address in enumerate(self.__register_address_array):
                data_entry = read_callback(addr=address,
                                           width=self.width,
                                           accesswidth=self.accesswidth)

                data_list[entry] = data_entry

            return data_list

        raise RuntimeError('There is no usable callback')

    def __block_write(self, data: list[int], verify: bool) -> None:
        """
        Write all the contents of the array in the most optimal way, ideally with a block operation
        """
        write_block_callback = self._callbacks.write_block_callback
        write_callback = self._callbacks.write_callback

        if write_block_callback is not None:
            write_block_callback(addr=self.address,
                                 width=self.width,
                                 accesswidth=self.width,
                                 data=data)

        elif write_callback is not None:
            # there is not write_block_callback defined so we must used individual write

            if self.__register_address_array is None:
                raise RuntimeError('This address array has not be initialised')

            for entry_index, entry_data in enumerate(data):
                entry_address = self.__register_address_array[entry_index]
                write_callback(addr=entry_address,
                               width=self.width,
                               accesswidth=self.accesswidth,
                               data=entry_data)

        else:
            raise RuntimeError('No suitable callback')

        if verify:
            read_back_verify_data = self.__block_read()
            if read_back_verify_data != data:
                raise RegisterWriteVerifyError('Read back block miss-match')

    def __cache_entry(self, addr: int, width: int, accesswidth: int) -> int:
        """
        Validate the data provided and determine the cache entry

        Args:
            addr: Address to write to
            width: Width of the register in bits
            accesswidth: Minimum access width of the register in bits

        Returns:
            cache entry

        """
        if not isinstance(width, int):
            raise TypeError(f'Width should be an int byt got {type(width)}')
        if width != self.width:
            raise ValueError('Requested Read width does not match the expected value')
        if not isinstance(accesswidth, int):
            raise TypeError(f'accesswidth should be an int byt got {type(accesswidth)}')
        if accesswidth != self.accesswidth:
            raise ValueError('Requested Read accesswidth does not match the expected value')
        if not isinstance(addr, int):
            raise TypeError(f'addr should be an int byt got {type(addr)}')
        if not self.address <= addr < (self.address + self.size):
            raise ValueError(f'Requested address 0x{addr:X} is out of range 0x{self.address:X} to '
                             f'0x{self.address + self.size - (self.width >> 3):X}')
        cache_entry = (addr - self.address) // (self.width >> 3)
        if self.__register_address_array is None:
            raise RuntimeError('The address table should always be populated here')
        if self.__register_address_array[cache_entry] != addr:
            raise RuntimeError(f'The calculated cache entry for address 0x{addr:X}')
        return cache_entry

    def __cache_read(self, addr: int, width: int, accesswidth: int) -> int:
        """
        Used to replace the normal callbacks with those that access the cache

        Args:
            addr: Address to write to
            width: Width of the register in bits
            accesswidth: Minimum access width of the register in bits

        Returns:
            value inputted by the used
        """
        if self.__register_cache is None:
            raise RuntimeError('The cache array should be initialised')
        return self.__register_cache[self.__cache_entry(addr=addr,
                                                        width=width,
                                                        accesswidth=accesswidth)]

    def __cache_write(self, addr: int, width: int, accesswidth: int, data: int) -> None:
        """
        Used to replace the normal callbacks with those that access the cache

        Args:
            addr: Address to write to
            width: Width of the register in bits
            accesswidth: Minimum access width of the register in bits
            data: value to be written to the register

        Returns:
            None
        """
        if not isinstance(data, int):
            raise TypeError(f'Data should be an int byt got {type(data)}')
        if self.__register_cache is None:
            raise RuntimeError('The cache array should be initialised')
        self.__register_cache[self.__cache_entry(addr=addr,
                                                 width=width,
                                                 accesswidth=accesswidth)] = data

    @property
    def __cache_callbacks(self) -> NormalCallbackSet:
        return NormalCallbackSet(read_callback=self.__cache_read,
                                 write_callback=self.__cache_write)

    @property
    def __number_cache_entries(self) -> int:
        return self.size // (self.width >> 3)

    def __initialise_cache(self, skip_initial_read: bool) -> list[int]:
        if skip_initial_read:
            return self.__empty_cache
        return self.__block_read()

    @contextmanager
    def _cached_access(self, verify: bool = False, skip_write: bool = False,
                       skip_initial_read: bool = False) -> \
            Generator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single set of
        field operations

        Args:
            verify (bool): verify the write with a read afterwards
            skip_write (bool): skip the write back at the end
        """
        self.__register_address_array = \
            [self.address + (i * (self.width >> 3)) for i in range(self.__number_cache_entries)]
        self.__register_cache = self.__initialise_cache(skip_initial_read=skip_initial_read)
        self.__in_context_manager = True
        # this try/finally is needed to make sure that in the event of an exception
        # the state flags are not left incorrectly set
        try:
            yield self
        finally:
            self.__in_context_manager = False
        if not skip_write:
            if not isinstance(self.__register_cache, list):
                raise TypeError('Register cache should be a list in non-legacy mode')
            self.__block_write(self.__register_cache, verify)

        # clear the register states at the end of the context manager
        self.__register_address_array = None
        self.__register_cache = None

    @property
    def _callbacks(self) -> NormalCallbackSet:

        if self.__in_context_manager:
            return self.__cache_callbacks

        if self.parent is None:
            raise RuntimeError('Parent must be set')
        # This cast is OK because the type was checked in the __init__
        # pylint: disable-next=protected-access
        return cast(NormalCallbackSet, self.parent._callbacks)


class RegReadOnly(Reg, ABC):
    """
    class for a read only register

    Args:
        address: address of the register
        width: width of the register in bits
        accesswidth: minimum access width of the register in bits
        logger_handle: name to be used logging messages associate with this
            object

    """

    __slots__: list[str] = ['__in_context_manager', '__register_state']

    # pylint: disable=too-many-arguments, duplicate-code
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AddressMap, RegFile, ReadableMemory]):

        super().__init__(address=address,
                         logger_handle=logger_handle,
                         inst_name=inst_name,
                         parent=parent)

        self.__in_context_manager: bool = False
        self.__register_state: int = 0

    # pylint: enable=too-many-arguments, duplicate-code

    @contextmanager
    def single_read(self) -> Generator[Self]:
        """
        Context manager to allow multiple field accesses to be performed with a single
        read of the register
        """
        self.__register_state = self.read()
        self.__in_context_manager = True
        # this try/finally is needed to make sure that in the event of an exception
        # the state flags are not left incorrectly set
        try:
            yield self
        finally:
            self.__in_context_manager = False

    def read(self) -> int:
        """
        Read value from the register
        """
        if self.__in_context_manager:
            return self.__register_state

        read_block_callback = self._callbacks.read_block_callback
        read_callback = self._callbacks.read_callback

        if read_callback is not None:
            return read_callback(addr=self.address,
                                 width=self.width,
                                 accesswidth=self.accesswidth)

        if read_block_callback is not None:
            return read_block_callback(addr=self.address,
                                       width=self.width,
                                       accesswidth=self.accesswidth,
                                       length=1)[0]

        raise RuntimeError('This function does not have a useable callback')

    @property
    def readable_fields(self) -> Iterator[Union['FieldReadOnly', 'FieldReadWrite']]:
        """
        generator that produces has all the readable fields within the register
        """
        def is_readable(field: Union['FieldReadOnly', 'FieldWriteOnly', 'FieldReadWrite']) -> \
                TypeGuard[Union['FieldReadOnly', 'FieldReadWrite']]:
            return isinstance(field, (FieldReadOnly, FieldReadWrite))

        return filter(is_readable, self.fields)

    def read_fields(self) -> dict['str', Union[bool, Enum, int]]:
        """
        read the register and return a dictionary of the field values
        """
        return_dict: dict['str', Union[bool, Enum, int]] = {}
        with self.single_read() as reg:
            for field in reg.readable_fields:
                return_dict[field.inst_name] = field.read()

        return return_dict

    @property
    def _is_readable(self) -> bool:
        # pylint: disable=duplicate-code
        return True

    @property
    def _is_writeable(self) -> bool:
        # pylint: disable=duplicate-code
        return False


class __RegWritable(Reg, ABC):
    """
    base class for a writable register (either RegWriteOnly or RegReadWrite)
    """

    __slots__: list[str] = []

    # pylint: disable=too-many-arguments, duplicate-code, useless-parent-delegation
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AddressMap, RegFile, WritableMemory]):

        super().__init__(address=address,
                         logger_handle=logger_handle,
                         inst_name=inst_name,
                         parent=parent)
    # pylint: enable=too-many-arguments, duplicate-code

    def write(self, data: int) -> None:
        """Writes a value to the register

        Args:
            data: data to be written

        Raises:
            ValueError: if the value provided is outside the range of the
                permissible values for the register
            TypeError: if the type of data is wrong
        """
        # this method check the types and range checks the data
        self._validate_data(data=data)

        self._logger.info(f'Writing data:0x{data:X} to 0x{self.address:X}')

        if self._callbacks.write_callback is not None:
            self._callbacks.write_callback(addr=self.address,
                                           width=self.width,
                                           accesswidth=self.accesswidth,
                                           data=data)  #

        elif self._callbacks.write_block_callback is not None:
            self._callbacks.write_block_callback(addr=self.address,
                                                 width=self.width,
                                                 accesswidth=self.accesswidth,
                                                 data=[data])

        else:
            raise RuntimeError('This function does not have a useable callback')

    @property
    def writable_fields(self) -> Iterator[Union['FieldWriteOnly', 'FieldReadWrite']]:
        """
        generator that produces has all the readable fields within the register
        """
        def is_writable(field: Union['FieldReadOnly', 'FieldWriteOnly', 'FieldReadWrite']) -> \
                TypeGuard[Union['FieldWriteOnly', 'FieldReadWrite']]:
            return isinstance(field, (FieldWriteOnly, FieldReadWrite))

        return filter(is_writable, self.fields)


class RegWriteOnly(__RegWritable, ABC):
    """
    class for a write only register
    """

    __slots__: list[str] = ['__in_context_manager', '__register_state', '__write_initial_state']

    # pylint: disable=too-many-arguments, duplicate-code, useless-parent-delegation
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AddressMap, RegFile, WritableMemory]):

        super().__init__(address=address,
                         logger_handle=logger_handle,
                         inst_name=inst_name,
                         parent=parent)

        self.__in_context_manager: bool = False
        self.__register_state: int = 0
        self.__write_initial_state: int = 0

    # pylint: enable=too-many-arguments, duplicate-code

    def write(self, data: int) -> None:
        """
        Writes a value to the register

        Args:
            data: data to be written

        Raises:
            ValueError: if the value provided is outside the range of the
                        permissible values for the register
            TypeError: if the type of data is wrong
            RegisterWriteVerifyError: the read back data after the write does not match the
                                      expected value
            RuntimeError: if the read verify after write is set when inside a context manager
        """


        if self.__in_context_manager:
            self.__register_state = data
        else:
            super().write(data)

    @property
    def write_initial_state(self) -> int:
        """
        This property defines the initial state of the register when using:
        - the `write_fields` method
        - the `write` method on any field in the register

        By default this is initialised to `0`, however, advanced usages may include:
        - A hidden field within the register which must not be set to `0`

        This property behaves accessed when inside the `single_write` when it returns the shadowed
        state of the register which has not yet been writen back (the initial state plus any write
        that have occurred). However, setting the property will still update the initial state not
        the shadowed state.
        """
        if self.__in_context_manager:
            return self.__register_state
        return self.__write_initial_state

    @write_initial_state.setter
    def write_initial_state(self, initial_state: int) -> None:
        # this method check the types and range checks the data
        self._validate_data(data=initial_state)
        self.__write_initial_state = initial_state

    def write_fields(self, **kwargs: Union[int,SystemRDLEnum]) -> None:
        """
        Do a single write to the register based on the fields provided, all fields must be
        specified to use this method

        Any parts of the register not set with this method will be based on the
        `write_initial_state` property
        """
        self._check_kwargs_field_names(**kwargs)

        with self.single_write(initial_state=self.write_initial_state) as reg:
            for field_name, field_value in kwargs.items():
                if field_name not in reg.systemrdl_python_child_name_map.values():
                    raise ValueError(f'{field_name} is not a member of the register')

                field = getattr(reg, field_name)
                field.write(field_value)

    @property
    def _is_readable(self) -> bool:
        # pylint: disable=duplicate-code
        return False

    @property
    def _is_writeable(self) -> bool:
        # pylint: disable=duplicate-code
        return True

    @contextmanager
    def single_write(self, initial_state: int) -> Generator[Self]:
        """
        Context manager to allow multiple field write operations to be carried out with a
        single write at the end, based on a specified initial state of the register.
        """
        # this method check the types and range checks the data
        self._validate_data(data=initial_state)

        self.__register_state = initial_state
        self.__in_context_manager = True
        # this try/finally is needed to make sure that in the event of an exception
        # the state flags are not left incorrectly set
        try:
            yield self
        finally:
            self.__in_context_manager = False
        self.write(self.__register_state)


class RegReadWrite(RegReadOnly, __RegWritable, ABC):
    """
    class for a read and write only register

    """
    __slots__: list[str] = ['__in_read_context_manager',
                            '__in_write_context_manager',
                            '__register_state',
                            '__write_initial_state']

    # pylint: disable=too-many-arguments, duplicate-code
    def __init__(self, *,
                 address: int,
                 logger_handle: str,
                 inst_name: str,
                 parent: Union[AddressMap, RegFile, MemoryReadWrite]):

        super().__init__(address=address,
                         logger_handle=logger_handle,
                         inst_name=inst_name,
                         parent=parent)

        self.__in_read_context_manager: bool = False
        self.__in_write_context_manager: bool = False
        self.__register_state: Optional[int] = None
        self.__write_initial_state = 0

    # pylint: enable=too-many-arguments, duplicate-code

    @contextmanager
    def single_read_modify_write(self, verify: bool = False) -> Generator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single register read
        and write

        Args:
            verify (bool): verify the write with a read afterwards
        """
        initial_state = self.read()
        with self.single_write(initial_state=initial_state, verify=verify) as reg:
            yield reg

    @contextmanager
    def single_read(self) -> Generator[Self]:
        """
        Context manager to allow multiple field reads with a single register read
        """
        if self.__in_read_context_manager:
            raise RuntimeError('using the `single_read` context manager double layered is '
                               'not permitted')

        if self.__in_write_context_manager:
            raise RuntimeError('using the `single_read` context manager within the '
                               'single_read_modify_write` or `single_write` is not permitted')
        self.__in_read_context_manager = True
        try:
            with super().single_read() as reg:
                yield reg
        finally:
            self.__in_read_context_manager = False

    @contextmanager
    def single_write(self, initial_state: int, verify: bool = False) -> Generator[Self]:
        """
        Context manager to allow multiple field updates with a single register write when the
         context manager exits
        """
        if self.__in_write_context_manager or self.__in_read_context_manager:
            raise RuntimeError('using the `single_write` context manager within the '
                               'single_read_modify_write` or `single_read` is not permitted. '
                               'Similarly, using the `single_write` context manager within itself '
                               'is not permitted')
        self.__in_write_context_manager = True
        self.__register_state = initial_state
        try:
            yield self
        finally:
            self.__in_write_context_manager = False
        self.write(self.__register_state, verify=verify)

        # clear the register states at the end of the context manager
        self.__register_state = None

    def write(self, data: int, verify: bool = False) -> None:  # pylint: disable=arguments-differ
        """
        Writes a value to the register

        Args:
            data: data to be written
            verify: set to True to read back the register to verify the read has occurred correctly

        Raises:
            ValueError: if the value provided is outside the range of the
                        permissible values for the register
            TypeError: if the type of data is wrong
            RegisterWriteVerifyError: the read back data after the write does not match the
                                      expected value
            RuntimeError: if the read verify after write is set when inside a context manager
        """
        if self.__in_read_context_manager:
            raise RuntimeError('writes within the single read context manager are not permitted')

        if self.__in_write_context_manager:
            if self.__register_state is None:
                raise RuntimeError('The internal register state should never be None in the '
                                   'context manager')
            if verify:
                raise RuntimeError('Using the verify option is not permitted inside the '
                                   '`single_write` or `single_read_modify_write` context manager')

            self.__register_state = data
        else:
            super().write(data)
            if verify:
                read_back = self.read()
                if read_back != data:
                    raise RegisterWriteVerifyError(f'Readback {read_back:X} '
                                                   f'after writing {data:X}')

    def read(self) -> int:
        """
        Read value from the register

        Note:
            The `read` method behaves differently when used within the one of the context managers:
            - when used within `single_read_modify_write` or `single_read` it will return the
              register value read at the entry into the context manager
            - when used within `single_write` it will return the register value based on the
              `initial_state` argument provided with the context manager
        """
        if self.__in_write_context_manager:
            if self.__register_state is None:
                raise RuntimeError('The internal register state should never be None in the '
                                   'context manager')
            return self.__register_state

        # the single read context manager is handled in the base class so does need any
        # handling here

        return super().read()

    def write_fields(self, **kwargs: Union[int, SystemRDLEnum]) -> None:
        """
        Do a read-modify-write to the register, updating any field included in
        the arguments
        """
        if len(kwargs) == 0:
            raise ValueError('no command args')

        with self.single_read_modify_write() as reg:
            for field_name, field_value in kwargs.items():
                if field_name not in reg.systemrdl_python_child_name_map.values():
                    raise ValueError(f'{field_name} is not a member of the register')

                field = getattr(reg, field_name)
                field.write(field_value)

    def read_fields(self) -> dict['str', Union[bool, Enum, int]]:
        """
        read the register and return a dictionary of the field values
        """
        return_dict: dict['str', Union[bool, Enum, int]] = {}
        with self.single_read() as reg:
            for field in reg.readable_fields:
                return_dict[field.inst_name] = field.read()

        return return_dict

    @property
    def _is_readable(self) -> bool:
        # pylint: disable=duplicate-code
        return True

    @property
    def _is_writeable(self) -> bool:
        # pylint: disable=duplicate-code
        return True

    def write_all_fields_without_read(self, **kwargs: int) -> None:
        """
        Do a write to all the fields in a register, updating any field included in
        the arguments based on the starting state of `write_initial_state`
        """
        # add a check that everything is here
        with self.single_write(initial_state=self.write_initial_state) as reg:
            for field_name, field_value in kwargs.items():
                if field_name not in reg.systemrdl_python_child_name_map.values():
                    raise ValueError(f'{field_name} is not a member of the register')

                field = getattr(reg, field_name)
                field.write(field_value)

    @property
    def write_initial_state(self) -> int:
        """
        This property defines the initial state of the register when using the
        `write_all_fields_without_read` method before any updates are applied.
        """
        return self.__write_initial_state

    @write_initial_state.setter
    def write_initial_state(self, initial_state: int) -> None:
        # this method check the types and range checks the data
        self._validate_data(data=initial_state)
        self.__write_initial_state = initial_state


ReadableRegister = Union[RegReadOnly, RegReadWrite]
WritableRegister = Union[RegWriteOnly, RegReadWrite]


class RegReadOnlyArray(RegArray[RegReadOnly], ABC):
    """
    base class for a array of read only registers
    """
    __slots__: list[str] = []

    # pylint: disable=too-many-arguments,duplicate-code
    def __init__(self, *,
                 logger_handle: str, inst_name: str,
                 parent: Union[RegFile, AddressMap, ReadableMemory],
                 address: int,
                 stride: int,
                 dimensions: tuple[int, ...],
                 elements: Optional[tuple[tuple[tuple[int, ...], ...],
                                    tuple[RegReadOnly, ...]]] = None):

        if not isinstance(parent, (RegFile, AddressMap, MemoryReadOnly, MemoryReadWrite)):
            raise TypeError('parent should be either RegFile, AddressMap, '
                            'MemoryReadOnly, MemoryReadWrite '
                            f'got {type(parent)}')

        if not isinstance(parent._callbacks, NormalCallbackSet):
            raise TypeError(f'callback set type is wrong, got {type(parent._callbacks)}')

        super().__init__(logger_handle=logger_handle, inst_name=inst_name,
                         parent=parent, address=address,
                         stride=stride, dimensions=dimensions, elements=elements)
    # pylint: enable=too-many-arguments,duplicate-code

    @contextmanager
    def single_read(self) -> Generator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single set of
        field operations
        """
        with self._cached_access(verify=False, skip_write=True,
                                 skip_initial_read=False) as reg_array:
            yield reg_array

    @property
    def _is_readable(self) -> bool:
        # pylint: disable=duplicate-code
        return True

    @property
    def _is_writeable(self) -> bool:
        # pylint: disable=duplicate-code
        return False


class RegWriteOnlyArray(RegArray[RegWriteOnly], ABC):
    """
    base class for a array of write only registers
    """
    __slots__: list[str] = []

    # pylint: disable=too-many-arguments,duplicate-code
    def __init__(self, *,
                 logger_handle: str, inst_name: str,
                 parent: Union[RegFile, AddressMap, WritableMemory],
                 address: int,
                 stride: int,
                 dimensions: tuple[int, ...],
                 elements: Optional[tuple[tuple[tuple[int, ...], ...],
                                          tuple[RegWriteOnly, ...]]] = None):

        if not isinstance(parent, (RegFile, AddressMap, MemoryWriteOnly, MemoryReadWrite)):
            raise TypeError('parent should be either RegFile, AddressMap, MemoryWriteOnly, '
                            'MemoryReadWrite '
                            f'got {type(parent)}')

        if not isinstance(parent._callbacks, NormalCallbackSet):
            raise TypeError(f'callback set type is wrong, got {type(parent._callbacks)}')

        super().__init__(logger_handle=logger_handle, inst_name=inst_name,
                         parent=parent, address=address,
                         stride=stride, dimensions=dimensions, elements=elements)
    # pylint: enable=too-many-arguments,duplicate-code

    @contextmanager
    def single_write(self) -> Generator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single set of
        field operations
        """
        with self._cached_access(verify=False, skip_write=False,
                                 skip_initial_read=True) as reg_array:
            yield reg_array

    @property
    def _is_readable(self) -> bool:
        # pylint: disable=duplicate-code
        return False

    @property
    def _is_writeable(self) -> bool:
        # pylint: disable=duplicate-code
        return True


class RegReadWriteArray(RegArray[RegReadWrite], ABC):
    """
    base class for a array of read and write registers
    """
    __slots__: list[str] = []

    # pylint: disable=too-many-arguments,duplicate-code
    def __init__(self, *,
                 logger_handle: str, inst_name: str,
                 parent: Union[RegFile, AddressMap, MemoryReadWrite],
                 address: int,
                 stride: int,
                 dimensions: tuple[int, ...],
                 elements: Optional[tuple[tuple[tuple[int, ...], ...],
                                          tuple[RegReadWrite, ...]]] = None):

        if not isinstance(parent, (RegFile, AddressMap, MemoryReadWrite)):
            raise TypeError('parent should be either RegFile, AddressMap, MemoryReadWrite '
                            f'got {type(parent)}')

        if not isinstance(parent._callbacks, NormalCallbackSet):
            raise TypeError(f'callback set type is wrong, got {type(parent._callbacks)}')

        super().__init__(logger_handle=logger_handle, inst_name=inst_name,
                         parent=parent, address=address,
                         stride=stride, dimensions=dimensions, elements=elements)

    # pylint: enable=too-many-arguments,duplicate-code

    @contextmanager
    def single_read_modify_write(self, verify: bool = False, skip_write: bool = False) -> \
            Generator[Self]:
        """
        Context manager to allow multiple field reads/write to be done with a single set of
        field operations

        Args:
            verify (bool): very the write with a read afterwards
            skip_write (bool): skip the write back at the end
        """
        with self._cached_access(verify=verify, skip_write=skip_write,
                                 skip_initial_read=False) as reg_array:
            yield reg_array

    @property
    def _is_readable(self) -> bool:
        # pylint: disable=duplicate-code
        return True

    @property
    def _is_writeable(self) -> bool:
        # pylint: disable=duplicate-code
        return True


ReadableRegisterArray = Union[RegReadOnlyArray, RegReadWriteArray]
WriteableRegisterArray = Union[RegWriteOnlyArray, RegReadWriteArray]


class FieldReadOnly(_FieldReadOnlyFramework[FieldType], ABC):
    """
    class for a read only register field

    Args:
        parent_register: register within which the field resides
        size_props: object defining the msb, lsb, high bit, low bit and width
        logger_handle: name to be used logging messages associate with this
            object

    """
    __slots__: list[str] = []

    # pylint: disable-next=too-many-arguments
    def __init__(self, *,
                 parent_register: ReadableRegister,
                 size_props: FieldSizeProps,
                 misc_props: FieldMiscProps,
                 logger_handle: str,
                 inst_name: str,
                 field_type:type[FieldType]):

        if not isinstance(parent_register, (RegReadWrite, RegReadOnly)):
            raise TypeError(f'size_props must be of {type(RegReadWrite)} or {type(RegReadOnly)} '
                            f'but got {type(parent_register)}')

        # pylint: disable=duplicate-code
        super().__init__(logger_handle=logger_handle,
                         size_props=size_props,
                         misc_props=misc_props,
                         parent_register=parent_register,
                         inst_name=inst_name,
                         field_type=field_type)
        # pylint: enable=duplicate-code

    def read(self) -> FieldType:
        """
        Reads the register that this field is located in and retries the field
        value applying the required masking and shifting

        Returns:
            field value

        """
        return self._decode_read_value(self.parent_register.read())

    @property
    def parent_register(self) -> ReadableRegister:
        """
        parent register the field is placed in
        """

        # this cast is OK because an explict typing check was done in the __init__
        return cast(ReadableRegister, self.parent)


class FieldWriteOnly(_FieldWriteOnlyFramework[FieldType], ABC):
    """
    class for a write only register field

    Args:
        parent_register: register within which the field resides
        size_props: object defining the msb, lsb, high bit, low bit and width
        logger_handle: name to be used logging messages associate with this
            object

    """
    __slots__: list[str] = []

    # pylint: disable-next=too-many-arguments
    def __init__(self, *,
                 parent_register: WritableRegister,
                 size_props: FieldSizeProps,
                 misc_props: FieldMiscProps,
                 logger_handle: str,
                 inst_name: str,
                 field_type:type[FieldType]):

        if not isinstance(parent_register, (RegReadWrite, RegWriteOnly)):
            raise TypeError(f'size_props must be of {type(RegReadWrite)} or {type(RegWriteOnly)} '
                            f'but got {type(parent_register)}')

        # pylint: disable=duplicate-code
        super().__init__(logger_handle=logger_handle,
                         size_props=size_props,
                         misc_props=misc_props,
                         parent_register=parent_register,
                         inst_name=inst_name,
                         field_type=field_type)
        # pylint: enable=duplicate-code

    def write(self, value: FieldType, verify: bool = False, force_no_read: bool = False) -> None:
        """
        The behaviour of this method depends on whether the field is located in
        a readable register or not:

        If the register is readable, the method will perform a read-modify-write
        on the register updating the field with the value provided, unless force_no_read` is set
        to `True` in which case the register `write_initial_state` is used

        If the register is not writable, all other field values will be written
        with based on the register `write_initial_state`.

        Args:
            value: field value to update to
            verify: Read back the register value to confirm the write was successful
            force_no_read: prevents a pre-write read in the case of a Read/Write Register

        Raises:
            ValueError: if verify is turned on for a Write Only register

        """
        encoded_value = self._encode_write_value(value)

        if (self.high == (self.register_data_width - 1)) and (self.low == 0):
            # special case where the field occupies the whole register,
            # there a straight write can be performed
            new_reg_value = encoded_value
        else:
            # do a read, modify write
            if isinstance(self.parent_register, RegReadWrite) and not force_no_read:
                reg_value = self.parent_register.read()
                masked_reg_value = reg_value & self.inverse_bitmask
                new_reg_value = masked_reg_value | encoded_value
            elif (isinstance(self.parent_register, RegWriteOnly) or
                  (isinstance(self.parent_register, RegReadWrite) and force_no_read)):
                reg_value = self.parent_register.write_initial_state
                masked_reg_value = reg_value & self.inverse_bitmask
                new_reg_value = masked_reg_value | encoded_value
            else:
                raise TypeError('Unhandled parent type')

        if isinstance(self.parent_register, RegReadWrite):
            self.parent_register.write(new_reg_value, verify=verify)
        elif isinstance(self.parent_register, RegWriteOnly):
            if verify:
                raise ValueError('A post-write verify (read) can not be performed on a write-only '
                                 'register')
            self.parent_register.write(new_reg_value)

    @property
    def parent_register(self) -> WritableRegister:
        """
        parent register the field is placed in
        """

        # this cast is OK because an explict typing check was done in the __init__
        return cast(WritableRegister, self.parent)


class FieldReadWrite(FieldReadOnly[FieldType], FieldWriteOnly[FieldType], ABC):
    """
    class for a read/write register field

    Args:
        parent_register: register within which the field resides
        size_props: object defining the msb, lsb, high bit, low bit and width
        logger_handle: name to be used logging messages associate with this
            object

    """
    __slots__: list[str] = []

    # pylint: disable-next=too-many-arguments
    def __init__(self, *,
                 parent_register: RegReadWrite,
                 size_props: FieldSizeProps,
                 misc_props: FieldMiscProps,
                 logger_handle: str,
                 inst_name: str,
                 field_type:type[FieldType]):

        if not isinstance(parent_register, RegReadWrite):
            raise TypeError(f'parent_register must be of {type(RegReadWrite)} '
                            f'but got {type(parent_register)}')

        super().__init__(logger_handle=logger_handle,
                         size_props=size_props,
                         misc_props=misc_props,
                         parent_register=parent_register,
                         inst_name=inst_name,
                         field_type=field_type)

    @property
    def parent_register(self) -> RegReadWrite:
        """
        parent register the field is placed in
        """

        # this cast is OK because an explict typing check was done in the __init__
        return cast(RegReadWrite, self.parent)


class FieldEnumReadWrite(FieldReadWrite[FieldType], FieldEnum[FieldType], ABC):
    """
    class for a read/write register field with an enumerated value
    """
    __slots__: list[str] = []

    @property
    def parent_register(self) -> RegReadWrite:
        """
        parent register the field is placed in
        """

        # this cast is OK because an explict typing check was done in the __init__
        return cast(RegReadWrite, self.parent)


class FieldEnumReadOnly(FieldReadOnly[FieldType], FieldEnum[FieldType], ABC):
    """
    class for a read only register field with an enumerated value
    """
    __slots__: list[str] = []


class FieldEnumWriteOnly(FieldWriteOnly[FieldType], FieldEnum[FieldType], ABC):
    """
    class for a write only register field with an enumerated value
    """
    __slots__: list[str] = []
