"""
peakrdl-python is a tool to generate Python Register Access Layer (RAL) from SystemRDL
Copyright (C) 2021 - 2023

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

This module is intended to distributed as part of automatically generated code by the
peakrdl-python tool. It provides a set of base classes used by the autogenerated code
"""


class Memory:
    """
    Simulation of a memory, this is implemented using a sparse approach to avoid the simulator
    storing every possible entry in a register map, which could be very big.
    """

    def __init__(self, *,
                 width: int,
                 length: int,
                 default_value: int,
                 full_inst_name: str):

        self.value: dict[int, int] = {}
        self.default_value = default_value

    def read(self, offset) -> int:
        if offset in self.value:
            return self.value[offset]

        return self.default_value

    def write(self, offset: int, data: int) -> None:
        self.value = data
