"""
peakrdl-python is a tool to generate Python Register Access Layer (RAL) from SystemRDL
Copyright (C) 2021 - 2023

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

This module is intended to distributed as part of automatically generated code by the
peakrdl-python tool. It provides a set of base classes used by the autogenerated code
"""
from abc import ABC, abstractmethod

from .memory import Memory
from .base import Base

class _BaseRegister(Base, ABC):
    """
    Base class for registers
    """

    __slots__ = ['width']
    def __init__(self, *,
                 width: int,
                 full_inst_name: str):
        super().__init__(full_inst_name=full_inst_name)
        self.width = width

    @abstractmethod
    def read(self) -> int:
        """
        Read the register

        Returns:
            register content

        """

    @abstractmethod
    def write(self, data: int) -> None:
        """
        Write the register

        Args:
            data (int): new register content

        Returns:
            None

        """


class Register(_BaseRegister):
    """
    Class for Register that is created in normal logic
    """

    __slots__ = ['value']

    def __init__(self, *,
                 width: int,
                 full_inst_name: str):
        super().__init__(width=width, full_inst_name=full_inst_name)
        self.value = 0

    def read(self) -> int:

        return self.value

    def write(self, data: int) -> None:

        self.value = data


class MemoryRegister(_BaseRegister):
    """
    Class for Register that maps onto a memory
    """

    __slots__ = ['memory', 'offset']

    def __init__(self, *,
                 width: int,
                 full_inst_name: str,
                 memory: Memory,
                 memory_address_offset: int):
        super().__init__(width=width, full_inst_name=full_inst_name)
        if not isinstance(memory, Memory):
            raise TypeError(f'memory type is wrong, got {type(memory)}')
        self.memory = memory
        self.offset = memory.byte_offset_to_word_offset(memory_address_offset)

    def read(self) -> int:
        return self.memory.read(self.offset)

    def write(self, data: int) -> None:
        self.memory.write(self.offset, data)
