"""
peakrdl-python is a tool to generate Python Register Access Layer (RAL) from SystemRDL
Copyright (C) 2021 - 2025

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

This package is intended to distributed as part of automatically generated code by the PeakRDL
Python tool. It provide the base class for the autogenerated tests
"""
# this module is very similar to the non-async version, a lot of code has been put into common
# methods but it did not make sense to do everything as it would destroy readability
# pylint:disable=duplicate-code

from abc import ABC
from typing import Union
from unittest.mock import patch,  call
from itertools import product

from ..sim_lib.memory import Memory as SimMemory
from ..lib import MemoryAsyncReadOnly
from ..lib import MemoryAsyncWriteOnly
from ..lib import MemoryAsyncReadWrite

from .utilities import random_memory_entry,random_memory_entry_value

from ._common_base_test_class import NodeIterators
from ._async_base_test_class import AsyncLibTestCommon

class AsyncLibTestMemory(AsyncLibTestCommon, ABC):
    """
    Tests for memories in an async access
    """
    async def _single_memory_read_and_write_test(self, *,
                                                 mut: Union[MemoryAsyncReadOnly,
                                                            MemoryAsyncWriteOnly,
                                                            MemoryAsyncReadWrite],
                                                 is_sw_readable: bool,
                                                 is_sw_writable: bool,
                                                 readable_registers: NodeIterators,
                                                 writeable_registers: NodeIterators) -> None:

        # the register memory are tested separately so are available to be used here

        self._test_register_iterators(dut=mut,
                                      readable_registers=readable_registers,
                                      writeable_registers=writeable_registers)

        if is_sw_readable:
            if not isinstance(mut, (MemoryAsyncReadOnly,
                                    MemoryAsyncReadWrite)):
                raise TypeError('Test can not proceed as the mut is not a readable memory')
            await self.__single_memory_read_test(mut=mut)
            await self.__single_memory_simulator_read_test(mut=mut)
        else:
            # test that a non-readable memory has no read method and
            # attempting one generates and error
            with self.assertRaises(AttributeError):
                _= await mut.read(0)  # type: ignore[union-attr,call-arg]

        if is_sw_writable:
            if not isinstance(mut, (MemoryAsyncWriteOnly,
                                    MemoryAsyncReadWrite)):
                raise TypeError('Test can not proceed as the mut is not a writable memory')
            await self.__single_memory_write_test(mut=mut)
            await self.__single_memory_simulator_write_test(mut=mut)
        else:
            # test that a non-writable memory has no write method and
            # attempting one generates and error
            with self.assertRaises(AttributeError):
                await mut.write(0)  # type: ignore[union-attr,call-arg]

    async def __single_memory_read_test(
            self,
            mut: Union[MemoryAsyncReadOnly,
                       MemoryAsyncReadWrite]
        ) -> None:

        with patch.object(self, 'write_callback') as write_callback_mock, \
            patch.object(self, 'read_callback', return_value=0) as read_callback_mock:

            # single entry read test
            for entry, value in product(
                    [0, mut.entries-1, random_memory_entry(mut)],
                    [0, mut.max_entry_value, random_memory_entry_value(mut)]):
                read_callback_mock.return_value = value

                self.assertEqual(await mut.read(start_entry=entry, number_entries=1),[value])

                read_callback_mock.assert_called_once_with(
                    addr=mut.address + (entry * mut.width_in_bytes),
                    width=mut.width,
                    accesswidth=mut.accesswidth)
                read_callback_mock.reset_mock()

            # multi-entry read
            # check a multi-entry read, if the memory is small do the entire memory, however, if
            # it is large limit the number of entries to 10
            entries_to_test = mut.entries if mut.entries < 10 else 10
            rand_data_list = [random_memory_entry_value(mut) for _ in range(entries_to_test)]
            # the following needs to have the same parameters as the callback so has some unused
            # args
            # pylint:disable-next=unused-argument
            def read_data_mock(addr: int, width: int, accesswidth: int) -> int:
                mem_entry = (addr - mut.address) // mut.width_in_bytes
                return rand_data_list[mem_entry]
            read_callback_mock.side_effect = read_data_mock

            self.assertEqual(await mut.read(start_entry=0, number_entries=entries_to_test),
                             rand_data_list)

            write_callback_mock.assert_not_called()

    async def __single_memory_write_test(
            self,
            mut: Union[MemoryAsyncWriteOnly,
                       MemoryAsyncReadWrite]
        ) -> None:

        with patch.object(self, 'write_callback') as write_callback_mock, \
            patch.object(self, 'read_callback', return_value=0) as read_callback_mock:

            # single entry write test
            for entry, value in product(
                    [0, mut.entries - 1, random_memory_entry(mut)],
                    [0, mut.max_entry_value, random_memory_entry_value(mut)]):

                await mut.write(start_entry=entry, data = [value])

                write_callback_mock.assert_called_once_with(
                    addr=mut.address + (entry * mut.width_in_bytes),
                    width=mut.width,
                    accesswidth=mut.accesswidth,
                    data=value)
                write_callback_mock.reset_mock()

            # multi-entry read
            # check a multi-entry read, if the memory is small do the entire memory, however, if
            # it is large limit the number of entries to 10
            entries_to_test = mut.entries if mut.entries < 10 else 10
            rand_data_list = [random_memory_entry_value(mut) for _ in range(entries_to_test)]

            await mut.write(start_entry=0, data=rand_data_list)

            calls = [call(addr=mut.address + (entry * mut.width_in_bytes),
                          width=mut.width,
                          accesswidth=mut.accesswidth,
                          data=rand_data_list[entry]) for entry in range(entries_to_test)]
            write_callback_mock.assert_has_calls(calls, any_order=False)

            # check invalid write values bounce
            with self.assertRaises(ValueError):
                await mut.write(start_entry=0, data=[mut.max_entry_value + 1])
            with self.assertRaises(ValueError):
                await mut.write(start_entry=0, data=[-1])

            read_callback_mock.assert_not_called()

    async def __single_memory_simulator_read_test(
            self,
            mut: Union[MemoryAsyncReadOnly, MemoryAsyncReadWrite],
        ) -> None:

        sim_memory = self.simulator_instance.memory_by_full_name(mut.full_inst_name)
        self.assertIsInstance(sim_memory, SimMemory)

        # single entry read test
        for entry, value in product(
                [0, mut.entries - 1, random_memory_entry(mut)],
                [0, mut.max_entry_value, random_memory_entry_value(mut)]):

            sim_memory.value[entry] = value

            self.assertEqual(await mut.read(start_entry=entry, number_entries=1), [value])

        # multi-entry read
        # check a multi-entry read, if the memory is small do the entire memory, however, if
        # it is large limit the number of entries to 10
        entries_to_test = mut.entries if mut.entries < 10 else 10
        rand_data_list = [random_memory_entry_value(mut) for _ in range(entries_to_test)]
        for entry in range(entries_to_test):
            sim_memory.value[entry] = rand_data_list[entry]

        self.assertEqual(await mut.read(start_entry=0, number_entries=entries_to_test),
                         rand_data_list)

    async def __single_memory_simulator_write_test(
            self,
            mut: Union[MemoryAsyncWriteOnly, MemoryAsyncReadWrite]
        ) -> None:

        sim_memory = self.simulator_instance.memory_by_full_name(mut.full_inst_name)
        self.assertIsInstance(sim_memory, SimMemory)

        # single entry write test
        for entry, value in product(
                [0, mut.entries - 1, random_memory_entry(mut)],
                [0, mut.max_entry_value, random_memory_entry_value(mut)]):

            if not isinstance(mut, (MemoryAsyncWriteOnly, MemoryAsyncReadWrite)):
                raise TypeError(
                    f'Memory should be non-legacy type but got {type(mut)}')
            await mut.write(start_entry=entry, data=[value])

            self.assertEqual(sim_memory.value[entry], value)

        # multi-entry read
        # check a multi-entry read, if the memory is small do the entire memory, however, if
        # it is large limit the number of entries to 10
        entries_to_test = mut.entries if mut.entries < 10 else 10
        rand_data_list = [random_memory_entry_value(mut) for _ in range(entries_to_test)]

        await mut.write(start_entry=0, data=rand_data_list)

        for entry in range(entries_to_test):
            self.assertEqual(sim_memory.value[entry], rand_data_list[entry])
